### ISSUE TITLE
インテントの実装

### ISSUE THREAD

**Issue by yugo256** [yugo256/Mysecretary#3]
・各画面の遷移が正しく行われるようにインテントを行う。
・レイアウトにミスがある場合は訂正する。
・設定されたidを変更するときは必ず作業メンバーに報告する。

**Comment by yugo256** [comment]
作業が終わり次第プレゼン用のスライドを作成する。

**Comment by yugo256** [comment]
インテントの期限は今日中

**Comment by kousei-sakata** [comment]
了解！
